name: Batch syntax/run check
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show environment
        shell: cmd
        run: |
          ver
          echo %COMSPEC%
          echo Workspace: %CD%
          dir /b /s

      - name: Run tests
        shell: cmd
        env:
          SCRIPT: run_tests.bat
        run: |
          setlocal EnableExtensions EnableDelayedExpansion
          echo === BEGIN %CD%\%SCRIPT% ===
          echo on
          call "%SCRIPT%"
          set RC=%errorlevel%
          @echo off
          exit /b %RC%

      - name: Find & print test logs (tail)
        if: always()
        shell: pwsh
        run: |
          $patterns = @('*.log','*install_log*.txt','~*.txt','*.out')
          $files = @()
          foreach($p in $patterns){
            $files += Get-ChildItem -Path . -Recurse -Include $p -File -ErrorAction SilentlyContinue
          }
          # Also sweep the tests tree explicitly
          $files += Get-ChildItem -Path .\tests -Recurse -Include *.txt,*.log -File -ErrorAction SilentlyContinue
          $files = $files | Sort-Object LastWriteTime -Descending -Unique
          if(-not $files){ Write-Host "No log files found."; exit 0 }
          foreach($f in $files){
            Write-Host "::group::LOG $($f.FullName)"
            Get-Content -Path $f.FullName -Tail 400
            Write-Host "::endgroup::"
          }

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            **/*.log
            **/*install_log*.txt
            **/~*.txt
            **/*.out
            tests/**/*.txt
            tests/**/*.log
          if-no-files-found: warn
          retention-days: 14
