name: Codex PR syphon (respect PR target)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write        # needed to push into the PR's base branch
  pull-requests: write   # needed to comment/close PRs

jobs:
  siphon:
    # Only act on PRs whose HEAD branch starts with codex/
    if: startsWith(toLower(github.event.pull_request.head.ref), 'codex/')
    runs-on: ubuntu-latest

    env:
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}   # where the PR wants to land
      DRY_RUN: "false"   # set "true" to test without pushing/closing

    steps:
      - name: Show context
        run: |
          echo "Repo:         ${{ github.repository }}"
          echo "PR #:         ${{ github.event.pull_request.number }}"
          echo "Head ref:     ${{ github.event.pull_request.head.ref }}"
          echo "Base (target):${BASE_BRANCH}"
          echo "DRY_RUN:      ${DRY_RUN}"

      - name: Checkout PR base (target) branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}
          fetch-depth: 0

      - name: Fetch PR head into local ref
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:codex_tmp
          git log --oneline -n 5 codex_tmp || true

      - name: Merge or cherry-pick head into BASE
        id: apply
        run: |
          set -e
          git config user.name  "codex-syphon-bot"
          git config user.email "noreply@github.com"

          echo "::group::Attempt merge"
          if git merge --no-ff codex_tmp -m "syphon: merge PR #${{ github.event.pull_request.number }} (codex/*) into ${BASE_BRANCH}"; then
            MODE="merge"
          else
            echo "::endgroup::"
            echo "::group::Merge conflict → cherry-pick latest commit"
            git reset --hard HEAD
            LATEST=$(git rev-parse codex_tmp)
            if git cherry-pick --strategy=recursive -X theirs "$LATEST"; then
              MODE="cherry-pick"
            else
              MODE="conflict"
            fi
          fi
          echo "mode=$MODE" >> $GITHUB_OUTPUT
          echo "::endgroup::"

          if [ "$MODE" != "conflict" ] && [ "${DRY_RUN}" != "true" ]; then
            git push origin HEAD:${BASE_BRANCH}
          elif [ "$MODE" != "conflict" ]; then
            echo "[DRY RUN] Would push to ${BASE_BRANCH}"
          fi

      - name: Comment & close PR (or report)
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR=${{ github.event.pull_request.number }}
          MODE='${{ steps.apply.outputs.mode }}'

          if [ "${DRY_RUN}" = "true" ]; then
            gh pr comment "$PR" --body "[DRY RUN] Would syphon \`${{ github.event.pull_request.head.ref }}\` → \`${{ env.BASE_BRANCH }}\` (mode: ${MODE})."
            exit 0
          fi

          if [ "$MODE" = "conflict" ] || [ -z "$MODE" ]; then
            gh pr comment "$PR" --body "Syphon attempted from \`${{ github.event.pull_request.head.ref }}\` → \`${{ env.BASE_BRANCH }}\` but hit conflicts. Please resolve manually. (PR left open.)"
            exit 0
          fi

          gh pr comment "$PR" --body "Syphoned commits from \`${{ github.event.pull_request.head.ref }}\` into \`${{ env.BASE_BRANCH }}\` (mode: ${MODE}). Please continue work there. Closing this PR."
          gh pr close "$PR"