name: Codex nudger (post-failure comment)

on:
  workflow_run:
    workflows: ["Batch syntax/run check"]
    types: [completed]

permissions:
  contents: read
  actions: read
  pull-requests: write
  issues: write

jobs:
  nudge:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0].number }}
    runs-on: ubuntu-latest
    steps:
      - name: Gather context
        id: ctx
        run: |
          echo "REPO=${GITHUB_REPOSITORY}" >> "$GITHUB_OUTPUT"
          echo "RUN_ID=${{ github.event.workflow_run.id }}" >> "$GITHUB_OUTPUT"
          echo "PR_NUMBER=${{ github.event.workflow_run.pull_requests[0].number }}" >> "$GITHUB_OUTPUT"
          echo "BRANCH=${{ github.event.workflow_run.pull_requests[0].head.ref }}" >> "$GITHUB_OUTPUT"
          echo "RUN_URL=${{ github.server_url }}/${GITHUB_REPOSITORY}/actions/runs/${{ github.event.workflow_run.id }}" >> "$GITHUB_OUTPUT"

      - name: Download logs & compute snippet
        id: logs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ steps.ctx.outputs.REPO }}
          RUN_ID: ${{ steps.ctx.outputs.RUN_ID }}
        run: |
          set -e
          gh run view "$RUN_ID" -R "$REPO" --log > run.log || true

          awk 'BEGIN{IGNORECASE=1}
               /First failure \(machine-readable\):|AssertionError|^\s*ERROR\b|^##\[error\]|failed|exit code[[:space:]]+1/ {
                 start=NR-2; if(start<1) start=1; end=NR+8;
                 for(i=start;i<=end;i++) print lines[i];
                 found=1; exit
               }
               { lines[NR]=$0 }
               END{ if(!found) print "Could not auto-fingerprint; see run link." }' run.log > snippet.txt

          SNIP=$(sed ':a;N;$!ba;s/\r//g' snippet.txt)
          printf "SNIPPET<<EOF\n%s\nEOF\n" "$SNIP" >> "$GITHUB_OUTPUT"

      - name: Comment to PR (tag Codex)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ steps.ctx.outputs.REPO }}
          PR: ${{ steps.ctx.outputs.PR_NUMBER }}
          BRANCH: ${{ steps.ctx.outputs.BRANCH }}
          RUN_URL: ${{ steps.ctx.outputs.RUN_URL }}
          SNIPPET: ${{ steps.logs.outputs.SNIPPET }}
        run: |
          BODY=$(printf "%s\n\n%s\n\n%s\n%s\n\n%s\n%s\n%s\n" \
            "@codex" \
            "Source of truth: the latest PR run (Job Summary + failing step logs). Use CI only." \
            "First failure (snippet):" \
            "```"$'\n'"$SNIPPET"$'\n'``` \
            "Commit to branch \`$BRANCH\` with message:" \
            "fix(ci): address (#)" \
            "Then WAIT for CI; repeat until green, stopping if the same top error repeats twice.\n\nLinks:\n- Latest run: $RUN_URL\n- All runs for $BRANCH: https://github.com/$REPO/actions?query=branch%3A${BRANCH//\//%2F}" )
          printf "%s" "$BODY" > body.md
          gh pr comment "$PR" -R "$REPO" --body-file body.md